# Generated by Django 4.1.8 on 2023-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='website',
            field=models.URLField(default='none'),
        ),
    ]
