# Generated by Django 4.1.8 on 2023-04-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='website',
            field=models.URLField(default='none', null=True),
        ),
    ]
