# Generated by Django 4.1.8 on 2023-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_infoextra_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
