# Generated by Django 4.1.8 on 2023-04-25 23:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_ingreso', models.DateField(auto_now=True)),
                ('url_imagen', models.URLField()),
            ],
        ),
    ]
