# Generated by Django 4.1.8 on 2023-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='url_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
